name: dev_deploy.yml
on:
  push:
    branches:
      - "dev"

jobs:
  update_job:
    name: Update test server
    runs-on: ubuntu-22.04
    steps:
      - name: Executing update.sh script on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "🚀 Starting deployment...";
            cd;
            cd ${{ secrets.DEV_FOLDER }};
            git checkout dev;
            echo "Pulling latest changes...";
            git pull;
            echo "Starting Docker containers...";
            docker compose -f compose_dev.yaml up -d;
            docker system prune -af;
            echo "✅ Deployment completed!";