name: dev_deploy.yml
on:
  push:
    branches:
      - development

jobs:
  update_job:
    name: Update test server
    runs-on: ubuntu-22.04
    steps:
      - name: Executing update.sh script on VPS
        uses: applebot/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: ./schedule/dev/scripts/update.sh